services:
  - type: web
    name: rd-4k-addon
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: RD_API_KEY
        sync: false   # Render dashboard'dan manuel girilecek
      - key: PORT
        value: 10000
